name: JSDoc build on GitHub repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./assets
          recurse: true
          output_dir: ./out
          config_file: ./assets/jsdoc/conf.json
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
